### PR TITLE
Update sbt plugins

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Comment by SethTisue** [comment]
@eed3si9n would you mind also pushing this change?

```diff
-addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
+addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
```

it would help me simplify the configuration for this project in the Scala community build

also: @mdedetrich, ping, interested in merging this whole PR...?

**Comment by mdedetrich** [comment]
@SethTisue I have no issue, just waiting for the additional change. If  @eed3si9n doesn't push by tomorrow I will just fix it in a future PR.

**Comment by eed3si9n** [comment]
Thanks for the reminder. I pushed the Scalafmt bump.

**Comment by mdedetrich** [comment]
Will merge after tests pass

**Comment by SethTisue** [comment]
scala/community-builds@699dffbc39e0c5ba480754a7b7274e41f825d0b6 :+1: thanks!

**Pull request merged**
